//set tracking defaults
tracking:
    searchWindowSize: 20
    searchEpsilon: 0.1
    searchMaxLevel: 3
    trackingSearchMinEigenThreshold: 0.001
drawing:
    point:
        current:
            color:
                r: 255
                g: 0
                b: 0
                a: 0
            radius: 6
            lineType: 8
            trailingPoints: 20
            thickness: 2
        trailing:
            color:
                r: 0
                g: 255
                b: 0
                a: 0
            radius: 5
            lineType: 8
            thickness: 2
    angle:
        point:
            color:
                r: 0
                g: 0
                b: 255
                a: 0
            radius: 6
            lineType: 8
            thickness: 2
        line:
            color:
                r: 123
                g: 123
                b: 0
                a: 0
            thickness: 1
            lineType: 8
        string:
            font:
                hscale: 1
                vscale: 1
                shear: 0
                lineType: 8
            fontFace: CV_FONT_HERSHEY_SIMPLEX
            color:
                r: 255
                g: 0
                b: 0
                a: 0
            fontScale: 5
            thickness: 1
    string:
        font:
            hscale: 1
            vscale: 1
            shear: 0
            lineType: 8
            fontFace: CV_FONT_HERSHEY_SIMPLEX
            color:
                r: 255
                g: 0
                b: 0
                a: 0
            fontScale: 5
            thickness: 1
    freeDraw:
        color:
            r: 123
            g: 123
            b: 123
            a: 0
            thickness: 0.5
            lineType: 8

secretKey: qwerty1234
server:
    port: 8081